// Generated by CoffeeScript 1.12.1
(function() {
  var ko;

  ko = require('knockout');

  ko.utils.hasClass = function(element, cls) {
    var check, obj_class;
    obj_class = element.className;
    check = ko.utils.arrayFilter(obj_class.split(/\s+/), function(c) {
      return c === cls;
    });
    return check.length > 0;
  };

  ko.bindingHandlers.debug = {
    update: function(element, valueAccessor) {
      return console.log(ko.unwrap(valueAccessor()));
    }
  };

  ko.virtualElements.allowedBindings.debug = true;

}).call(this);

//# sourceMappingURL=Common.js.map
