// Generated by CoffeeScript 1.12.1
(function() {
  var ko;

  ko = require('knockout');

  ko.bindingHandlers.toggle = {
    update: function(element, valueAccessor, allBindings) {
      var event, value;
      value = valueAccessor();
      event = allBindings.get('toggleEvent') || 'click';
      switch (event) {
        case 'hover':
          return ko.applyBindingsToNode(element, {
            event: {
              mouseover: function() {
                return value(!value());
              },
              mouseout: function() {
                return value(!value());
              }
            }
          });
        default:
          return ko.applyBindingsToNode(element, {
            click: function() {
              return value(!value());
            }
          });
      }
    }
  };

}).call(this);

//# sourceMappingURL=Toggle.js.map
