// Generated by CoffeeScript 1.12.1
(function() {
  var BaseModel;

  BaseModel = (function() {
    function BaseModel(params) {
      this.disposes = [];
    }

    BaseModel.prototype.dispose = function() {
      return ko.utils.arrayForEach(this.disposes, function(obj) {
        return obj.dispose();
      });
    };

    return BaseModel;

  })();

  module.exports = BaseModel;

}).call(this);

//# sourceMappingURL=base.js.map
